/* eslint-disable */
// @ts-nocheck
// Generated by unplugin-vue-components
// Read more: https://github.com/vuejs/core/pull/3399
// biome-ignore lint: disable
export {}

/* prettier-ignore */
declare module 'vue' {
  export interface GlobalComponents {
    PjHeader: typeof import('./components/PjHeader.vue')['default']
    PjMain: typeof import('./components/PjMain.vue')['default']
    PkLoader: typeof import('components')['PkLoader']
    RouterLink: typeof import('vue-router')['RouterLink']
    RouterView: typeof import('vue-router')['RouterView']
    VvAction: typeof import('@volverjs/ui-vue/components')['VvAction']
    VvAlert: typeof import('@volverjs/ui-vue/components')['VvAlert']
    VvAlertGroup: typeof import('@volverjs/ui-vue/components')['VvAlertGroup']
    VvAvatar: typeof import('@volverjs/ui-vue/components')['VvAvatar']
    VvButton: typeof import('@volverjs/ui-vue/components')['VvButton']
    VvButtonGroup: typeof import('@volverjs/ui-vue/components')['VvButtonGroup']
    VvCard: typeof import('@volverjs/ui-vue/components')['VvCard']
    VvDropdown: typeof import('@volverjs/ui-vue/components')['VvDropdown']
    VvDropdownAction: typeof import('@volverjs/ui-vue/components')['VvDropdownAction']
    VvIcon: typeof import('@volverjs/ui-vue/components')['VvIcon']
    VvNav: typeof import('@volverjs/ui-vue/components')['VvNav']
    VvNavItem: typeof import('@volverjs/ui-vue/components')['VvNavItem']
    VvNavSeparator: typeof import('@volverjs/ui-vue/components')['VvNavSeparator']
  }
}
