/* eslint-disable */
/* prettier-ignore */
// oxfmt-ignore
// @ts-nocheck
// noinspection ES6UnusedImports
// Generated by vue-router. !! DO NOT MODIFY THIS FILE !!
// It's recommended to commit this file.
// Make sure to add this file to your tsconfig.json file as an "includes" or "files" entry.

import type {
  RouteRecordInfo,
  ParamValue,
  ParamValueOneOrMore,
  ParamValueZeroOrMore,
  ParamValueZeroOrOne,
} from 'vue-router'
import type {
  _ExtractParamParserType,
} from 'vue-router/experimental'

declare module 'vue-router' {
  interface TypesConfig {
    _ParamParsers: {}
    RouteNamedMap: import('vue-router/auto-routes').RouteNamedMap
    _RouteFileInfoMap: import('vue-router/auto-routes')._RouteFileInfoMap
  }
}

declare module 'vue-router/auto-routes' {
  /**
   * Route name map generated by vue-router
   */
  export interface RouteNamedMap {
    '/': RouteRecordInfo<
      '/',
      '/',
      Record<never, never>,
      Record<never, never>,
      | never
    >,
    '/[...all]': RouteRecordInfo<
      '/[...all]',
      '/:all(.*)',
      { all: ParamValue<true> },
      { all: ParamValue<false> },
      | never
    >,
    '/auth': RouteRecordInfo<
      '/auth',
      '/auth',
      Record<never, never>,
      Record<never, never>,
      | '/auth/'
      | '/auth/request-password-reset'
      | '/auth/reset-password'
      | '/auth/sign-up'
    >,
    '/auth/': RouteRecordInfo<
      '/auth/',
      '/auth',
      Record<never, never>,
      Record<never, never>,
      | never
    >,
    '/auth/request-password-reset': RouteRecordInfo<
      '/auth/request-password-reset',
      '/auth/request-password-reset',
      Record<never, never>,
      Record<never, never>,
      | never
    >,
    '/auth/reset-password': RouteRecordInfo<
      '/auth/reset-password',
      '/auth/reset-password',
      Record<never, never>,
      Record<never, never>,
      | never
    >,
    '/auth/sign-up': RouteRecordInfo<
      '/auth/sign-up',
      '/auth/sign-up',
      Record<never, never>,
      Record<never, never>,
      | never
    >,
    '/backoffice': RouteRecordInfo<
      '/backoffice',
      '/backoffice',
      Record<never, never>,
      Record<never, never>,
      | '/backoffice/'
      | '/backoffice/dashboard'
      | '/backoffice/users'
    >,
    '/backoffice/': RouteRecordInfo<
      '/backoffice/',
      '/backoffice',
      Record<never, never>,
      Record<never, never>,
      | never
    >,
    '/backoffice/dashboard': RouteRecordInfo<
      '/backoffice/dashboard',
      '/backoffice/dashboard',
      Record<never, never>,
      Record<never, never>,
      | never
    >,
    '/backoffice/users': RouteRecordInfo<
      '/backoffice/users',
      '/backoffice/users',
      Record<never, never>,
      Record<never, never>,
      | never
    >,
    '/frontoffice': RouteRecordInfo<
      '/frontoffice',
      '/frontoffice',
      Record<never, never>,
      Record<never, never>,
      | '/frontoffice/'
      | '/frontoffice/dashboard'
    >,
    '/frontoffice/': RouteRecordInfo<
      '/frontoffice/',
      '/frontoffice',
      Record<never, never>,
      Record<never, never>,
      | never
    >,
    '/frontoffice/dashboard': RouteRecordInfo<
      '/frontoffice/dashboard',
      '/frontoffice/dashboard',
      Record<never, never>,
      Record<never, never>,
      | never
    >,
  }

  /**
   * Route file to route info map by vue-router.
   * Used by the \`sfc-typed-router\` Volar plugin to automatically type \`useRoute()\`.
   *
   * Each key is a file path relative to the project root with 2 properties:
   * - routes: union of route names of the possible routes when in this page (passed to useRoute<...>())
   * - views: names of nested views (can be passed to <RouterView name="...">)
   *
   * @internal
   */
  export interface _RouteFileInfoMap {
    'src/pages/index.vue': {
      routes:
        | '/'
      views:
        | never
      pathParamNames:
        | never
    }
    'src/pages/[...all].vue': {
      routes:
        | '/[...all]'
      views:
        | never
      pathParamNames:
        | 'all'
    }
    'src/pages/auth.vue': {
      routes:
        | '/auth'
        | '/auth/'
        | '/auth/request-password-reset'
        | '/auth/reset-password'
        | '/auth/sign-up'
      views:
        | 'default'
      pathParamNames:
        | never
    }
    'src/pages/auth/index.vue': {
      routes:
        | '/auth/'
      views:
        | never
      pathParamNames:
        | never
    }
    'src/pages/auth/request-password-reset.vue': {
      routes:
        | '/auth/request-password-reset'
      views:
        | never
      pathParamNames:
        | never
    }
    'src/pages/auth/reset-password.vue': {
      routes:
        | '/auth/reset-password'
      views:
        | never
      pathParamNames:
        | never
    }
    'src/pages/auth/sign-up.vue': {
      routes:
        | '/auth/sign-up'
      views:
        | never
      pathParamNames:
        | never
    }
    'src/pages/backoffice.vue': {
      routes:
        | '/backoffice'
        | '/backoffice/'
        | '/backoffice/dashboard'
        | '/backoffice/users'
      views:
        | 'default'
      pathParamNames:
        | never
    }
    'src/pages/backoffice@sidebar.vue': {
      routes:
        | '/backoffice'
        | '/backoffice/'
        | '/backoffice/dashboard'
        | '/backoffice/users'
      views:
        | 'default'
      pathParamNames:
        | never
    }
    'src/pages/backoffice/index.vue': {
      routes:
        | '/backoffice/'
      views:
        | never
      pathParamNames:
        | never
    }
    'src/pages/backoffice/dashboard.vue': {
      routes:
        | '/backoffice/dashboard'
      views:
        | never
      pathParamNames:
        | never
    }
    'src/pages/backoffice/users.vue': {
      routes:
        | '/backoffice/users'
      views:
        | never
      pathParamNames:
        | never
    }
    'src/pages/frontoffice.vue': {
      routes:
        | '/frontoffice'
        | '/frontoffice/'
        | '/frontoffice/dashboard'
      views:
        | 'default'
      pathParamNames:
        | never
    }
    'src/pages/frontoffice@sidebar.vue': {
      routes:
        | '/frontoffice'
        | '/frontoffice/'
        | '/frontoffice/dashboard'
      views:
        | 'default'
      pathParamNames:
        | never
    }
    'src/pages/frontoffice/index.vue': {
      routes:
        | '/frontoffice/'
      views:
        | never
      pathParamNames:
        | never
    }
    'src/pages/frontoffice/dashboard.vue': {
      routes:
        | '/frontoffice/dashboard'
      views:
        | never
      pathParamNames:
        | never
    }
  }

  /**
   * Get a union of possible route names in a certain route component file.
   * Used by the \`sfc-typed-router\` Volar plugin to automatically type \`useRoute()\`.
   *
   * @internal
   */
  export type _RouteNamesForFilePath<FilePath extends string> =
    _RouteFileInfoMap extends Record<FilePath, infer Info>
      ? Info['routes']
      : keyof RouteNamedMap
}

export {}
